data:
  train_width: 512 
  train_height: 512 
  sample_rate: 25 
  n_sample_frames: 1
  n_motion_frames: 2
training:
  batch_size: 2
  num_workers: 0
  learning_rate: 1.0e-5
  num_epochs: 2
  hr_epochs: 2
  student_epochs: 2
  use_gpu_video_tensor: True
  prev_frames: 2  # Add this line to specify the number of previous frames to consider
  video_dir:  '/media/oem/12TB/Downloads/CelebV-HQ/celebvhq/35666'
  sample_rate: 25  
  n_sample_frames: 100
  json_file: './data/overfit.json'